"""add support_requests table

Revision ID: 250036e9fa81
Revises: 405939d5b3eb
Create Date: 2026-08-31 20:38:15.345891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250036e9fa81'
down_revision: Union[str, Sequence[str], None] = '405939d5b3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('platform_access', 'ask_mentor', name='support_request_category'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('screenshot_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_requests_category'), 'support_requests', ['category'], unique=False)
    op.create_index(op.f('ix_support_requests_course_id'), 'support_requests', ['course_id'], unique=False)
    op.create_index(op.f('ix_support_requests_user_id'), 'support_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_requests_user_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_course_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_category'), table_name='support_requests')
    op.drop_table('support_requests')
    # ### end Alembic commands ###
