"""Add optional course_id to faculty_applications

Revision ID: 405939d5b3eb
Revises: 05344cbe2e70
Create Date: 2026-08-25 22:33:24.665980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405939d5b3eb'
down_revision: Union[str, Sequence[str], None] = '05344cbe2e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_applications', sa.Column('course_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_faculty_applications_course_id'), 'faculty_applications', ['course_id'], unique=False)
    op.create_foreign_key(None, 'faculty_applications', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty_applications', type_='foreignkey')
    op.drop_index(op.f('ix_faculty_applications_course_id'), table_name='faculty_applications')
    op.drop_column('faculty_applications', 'course_id')
    # ### end Alembic commands ###
