"""add conversations and messages for mentor chat

Revision ID: 4cdba3e1e66e
Revises: d3ba668e4806
Create Date: 2026-08-31 21:54:44.633453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdba3e1e66e'
down_revision: Union[str, Sequence[str], None] = 'd3ba668e4806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=True),
    sa.Column('learner_name', sa.Text(), nullable=False),
    sa.Column('learner_email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_course_id'), 'conversations', ['course_id'], unique=False)
    op.create_index('ix_conversations_course_id_learner_id', 'conversations', ['course_id', 'learner_id'], unique=True)
    op.create_index(op.f('ix_conversations_learner_id'), 'conversations', ['learner_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('sender_name', sa.Text(), nullable=False),
    sa.Column('sender_role', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###

    # "Ask a Mentor" support_requests are superseded by this chat feature —
    # carry any existing ones over as the first message of a new
    # conversation instead of silently dropping real learner data. A CTE
    # assigns one conversation id per row up front so the two inserts below
    # don't need to re-match rows (fragile if learner_id/user_id is null).
    op.execute(
        """
        WITH migrated AS (
            SELECT sr.*, gen_random_uuid() AS conversation_id
            FROM support_requests sr
            WHERE sr.category = 'ask_mentor'
        ),
        inserted_conversations AS (
            INSERT INTO conversations (id, course_id, learner_id, learner_name, learner_email, created_at)
            SELECT conversation_id, course_id, user_id, requester_name, requester_email, created_at
            FROM migrated
        )
        INSERT INTO messages (id, conversation_id, sender_id, sender_name, sender_role, body, created_at)
        SELECT gen_random_uuid(), conversation_id, user_id, requester_name, 'learner', message, created_at
        FROM migrated
        """
    )
    op.execute("DELETE FROM support_requests WHERE category = 'ask_mentor'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_learner_id'), table_name='conversations')
    op.drop_index('ix_conversations_course_id_learner_id', table_name='conversations')
    op.drop_index(op.f('ix_conversations_course_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
