"""add requester name and email to support_requests

Revision ID: d3ba668e4806
Revises: 250036e9fa81
Create Date: 2026-08-31 21:13:52.833642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ba668e4806'
down_revision: Union[str, Sequence[str], None] = '250036e9fa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Added nullable, backfilled from the linked user, then made NOT NULL —
    # any pre-existing row was created before this denormalization existed.
    op.add_column('support_requests', sa.Column('requester_name', sa.String(length=255), nullable=True))
    op.add_column('support_requests', sa.Column('requester_email', sa.String(length=255), nullable=True))
    op.execute(
        """
        UPDATE support_requests sr
        SET requester_name = u.full_name, requester_email = u.email
        FROM users u
        WHERE sr.user_id = u.id
        """
    )
    op.alter_column('support_requests', 'requester_name', nullable=False)
    op.alter_column('support_requests', 'requester_email', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_requests', 'requester_email')
    op.drop_column('support_requests', 'requester_name')
    # ### end Alembic commands ###
