"""add is_temporary_password to users

Revision ID: ea29f8aa4e82
Revises: 994da0346893
Create Date: 2026-08-18 17:32:21.976270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea29f8aa4e82'
down_revision: Union[str, Sequence[str], None] = '994da0346893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so this backfills False for every existing row (real
    # users already have their own password, not an admin-set one) — the
    # ORM-level default=False only applies to rows inserted going forward.
    op.add_column(
        'users',
        sa.Column('is_temporary_password', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_temporary_password')
    # ### end Alembic commands ###
